npmAlwaysAuth: true
npmRegistryServer: "https://pkgs.dev.azure.com/reporting-cz/_packaging/reporting-feed/npm/registry/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
